plugins {
    id 'java-library'
    id 'maven-publish'
}

def libraryGroup    = 'io.github.neboskreb'
def libraryArtifact = 'eventbus3-idea-annotations'
def libraryVersion  = '2025.0.1'

tasks.register('sourceJar', Jar) {
	duplicatesStrategy = 'include'
    archiveClassifier.set('sources')
    from sourceSets.main.allJava
}

publishing {
    publications {
        maven(MavenPublication) {
            groupId    = libraryGroup
            artifactId = libraryArtifact
            version    = libraryVersion

            from components.java
            artifact tasks.sourceJar
        }
    }

    repositories {
        maven {
            name = "github-packages"
            credentials {
                username = "${github_packages_user}"
                password = "${github_packages_token}"
            }
            url = "https://maven.pkg.github.com/neboskreb/eventbus3-intellij-plugin"
        }
    }
}

java {
    sourceCompatibility = JavaVersion.VERSION_1_9
    targetCompatibility = JavaVersion.VERSION_1_9
}
